name: Compile
run-name: Compile
on: [push]
jobs:
  Compile:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, ubuntu-20.04, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Get App Version
        id: version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: package.json
          prop_path: version
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Version Bump
        run: node versionbump.js

      - name: Install Packages
        run: npm install

      - name: Compile Binaries
        run: npm run tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./src-tauri/target/release/bundle/deb/geode-studio_${{ steps.version.outputs.prop }}_amd64.deb
            ./src-tauri/target/release/bundle/appimage/geode-studio_${{ steps.version.outputs.prop }}_amd64.AppImage
            ./src-tauri/target/release/bundle/msi/geode-studio_${{ steps.version.outputs.prop }}_x64_en-US.msi
            ./src-tauri/target/release/bundle/dmg/geode-studio_${{ steps.version.outputs.prop }}_x64.dmg
          tag_name: v${{ steps.version.outputs.prop }}
          prerelease: true