name: Compile
run-name: Compile
on: [push]
jobs:
  Compile:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Get App Version
        id: version
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: src-tauri/tauri.conf.json
          prop_path: package.version

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Packages
        run: npm install

      - name: Compile Binaries
        run: npm run tauri build

      - name: Rename MSI
        run: rename "src-tauri/target/release/bundle/msi/geode-studio_${{ steps.version.outputs.prop }}_x64_en-US.msi" "src-tauri/target/release/bundle/msi/Geode-Studio.msi"

      - name: Rename Standalone
        run: rename "src-tauri/target/release/geode-studio.exe" "src-tauri/target/release/Geode-Studio-Standalone.exe"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./src-tauri/target/release/bundle/msi/Geode-Studio.msi
            ./src-tauri/target/release/Geode-Studio-Standalone.exe
          tag_name: v${{ steps.version.outputs.prop }}-Win
          prerelease: true
          overwrite: true